routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\rolController;
use App\Http\Controllers\permisoController;
use App\Http\Controllers\personaController;
use App\Http\Controllers\provinciasController;
use App\Http\Controllers\publicacionController;
use App\Http\Controllers\usuarioController;
use App\Http\Controllers\categoriaController;

/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', [PublicacionController::class, 'welcome']);

Route::get('nosotros', function () {
    return view('mainPage.Nosotros');
});

Route::get('destinos', [provinciasController::class, 'showDestinos']);
Route::resource('provincias', provinciasController::class);
Route::get('categoria/{provincia}', [PublicacionController::class, 'filtrar'])->name('publicaciones.filtrar');
Route::get('post/{publicacion}', [publicacionController::class, 'post'])->name('publicaciones.show');
Route::get('gastronomia', [publicacionController::class, 'gastronomia'])->name('gastronomia');
Route::resource('rol', rolController::class);
Route::resource('permiso', permisoController::class);
Route::resource('persona', personaController::class);
Route::resource('publicacion', publicacionController::class);
Route::resource('usuario', usuarioController::class);
Route::resource('category', categoriaController::class);

Route::get('/inicio', function () {
    return view('admin/layouts/admin');
});

Route::get('blog', [publicacionController::class, 'blog']);

Route::get('galeria', [publicacionController::class, 'galeria']);

/*Route::middleware(['auth:sanctum', 'verified'])->get('/publicaciones',  publicacionController::class)->name('publicaciones');*/

/*
Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('admin/layouts/admin');
})->name('dash');
*/

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/provincias.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class provincias extends Model
{
    protected $table = 'provincias';
    protected $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = false;
    protected $fillable = [
        'nombre', 
        'descripcion',  
    ];
    protected $guarded = [];
    use HasFactory;
}

app/Http/Controllers/provinciasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\provincias;
use Illuminate\Http\Request;

class provinciasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $provincia = provincias::all();
        return view ('admin/provincias/index', ['provincias' => $provincia]);
    }

    public function showDestinos()
    {
        $provincia = provincias::all();
        return view ('mainPage/destinos', ['provincias'=> $provincia]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin/provincias/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=> "required|unique:provincias",
            'descripcion'=>'required'
        ]);
        $provincia = new  provincias();
        $provincia->nombre = $request->get('nombre');
        $provincia->descripcion = $request->get('descripcion');
        $provincia->save();

        return redirect('provincias')->with('info', '¡Se ha registrado la provincia exitosamente!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(provincias $provincia)
    {
        return view ('admin/provincias/edit', ['provincia'=> $provincia]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, provincias $provincia)
    {
        $datos = request()->except(['_token','_method']);
        $request->validate([
            'nombre'=> "required|unique:provincias,nombre,$provincia->id",
            //'nombre'=> 'required',
            'descripcion'=>'required'
        ]);
        $provincia -> update($datos);
        return redirect()->route('provincias.index')->with('info','¡Datos actualizados exitosamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(provincias $provincia)
    {
        $provincia->delete();
        return redirect()->route('provincias.index', $provincia)->with('info','¡Dato eliminado exitosamente!');
    }
}

resources/views/admin/provincias/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <form class="p-4" action="{{route('provincias.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre de la provincia</label>
                    <input type="text" class="form-control" name="nombre" aria-describedby="emailHelp">
                    @error('nombre')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Descripción</label>
                    <textarea class="form-control" name="descripcion" rows="3"></textarea>
                    @error('descripcion')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="d-flex justify-content-between">
                <input type="submit" class="btn btn-primary" value="Guardar">
                    <a type="button" class="btn btn-success" href="/provincias">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
console.log('Hi!');
</script>
@stop

resources/views/admin/provincias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
@if(session('info'))
<div class="bg-success">
    <strong>{{session('info')}}</strong>
</div>
@endif
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <form class="p-4" action="{{route('provincias.update', $provincia)}}" method="POST" enctype="multipart/form-data">
                @csrf
                
                @method('put')
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre de la provincia</label>
                    <input type="text" id="nombre" class="form-control" name="nombre" value="{{$provincia->nombre}}">
                    @error('nombre')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Descripción</label>
                    <textarea class="form-control" name="descripcion" rows="3">{{$provincia->descripcion}}</textarea>
                    @error('descripcion')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="d-flex justify-content-between">
                <input type="submit" class="btn btn-primary">
                    <a type="button" class="btn btn-success" href="/provincias">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
console.log('Hi!');
</script>
@stop

resources/views/admin/provincias/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <div class="p-4">
                <div class="w-100 mb-4 row justify-content-md-between">
                    <label class="h4">Lista de provincias</label>
                    <a type="button" class="btn btn-success" href="provincias/create">Ingresar</a>
                </div>
                @if(session('info'))
                    <div id="toast" class="alert alert-success" style="height: 10vh">
                        <strong>{{session('info')}}</strong>
                        <button onclick="cerrar()" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                @endif
                <!--Contenedor de listado de publicaciones-->
                @if($provincias->count())
                    <div>
                        <table id="provincias" class="table table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col text-center">id</th>
                                    <th scope="col">provincia</th>
                                    <th scope="col">descripcion</th>
                                    <th scope="col text-center"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($provincias as $provincia)
                                <tr>
                                    <td>{{$provincia->id}}</td>
                                    <td>{{$provincia->nombre}}</td>
                                    <td>{{$provincia->descripcion}}</td>
                                    <td>
                                        <div class="w-100 row justify-content-center">
                                            <a class="btn btn-primary mr-2" href="{{route('provincias.edit', $provincia)}}">Editar</a>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                                Eliminar
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else 
                    <div class="text-center">
                        <strong>No hay ningún registros</strong>
                    </div>
                @endif
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ¿Desea eliminar el registro?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    @if($provincias->count())
                        <form action="{{route('provincias.destroy', $provincia)}}" method="POST">
                            <!--<button type="submit" class="btn btn-danger">Eliminar</button>-->
                            <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                Eliminar
                            </button>
                            @csrf
                            @method('delete')
                        </form>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@stop

@section('js')
</script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script>
    $(document).ready(function() {
        $('#provincias').DataTable({
            responsive: true,
            autowidth: false
        });
    });
</script>
<script>
    function cerrar() {
        document.getElementById("toast").style.display = "none";
    }
</script>
@stop