routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\rolController;
use App\Http\Controllers\permisoController;
use App\Http\Controllers\personaController;
use App\Http\Controllers\provinciasController;
use App\Http\Controllers\publicacionController;
use App\Http\Controllers\usuarioController;
use App\Http\Controllers\categoriaController;

/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/', [PublicacionController::class, 'welcome']);

Route::get('nosotros', function () {
    return view('mainPage.Nosotros');
});

Route::get('destinos', [provinciasController::class, 'showDestinos']);
Route::resource('provincias', provinciasController::class);
Route::get('categoria/{provincia}', [PublicacionController::class, 'filtrar'])->name('publicaciones.filtrar');
Route::get('post/{publicacion}', [publicacionController::class, 'post'])->name('publicaciones.show');
Route::get('gastronomia', [publicacionController::class, 'gastronomia'])->name('gastronomia');
Route::resource('rol', rolController::class);
Route::resource('permiso', permisoController::class);
Route::resource('persona', personaController::class);
Route::resource('publicacion', publicacionController::class);
Route::resource('usuario', usuarioController::class);
Route::resource('category', categoriaController::class);

Route::get('/inicio', function () {
    return view('admin/layouts/admin');
});

Route::get('blog', [publicacionController::class, 'blog']);

Route::get('galeria', [publicacionController::class, 'galeria']);

/*Route::middleware(['auth:sanctum', 'verified'])->get('/publicaciones',  publicacionController::class)->name('publicaciones');*/

/*
Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('admin/layouts/admin');
})->name('dash');
*/

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/permiso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class permiso extends Model
{
    protected $table = 'permiso';
    protected $primaryKey = 'id';
    public $incrementing = true;
    public $timestamps = false;
    protected $fillable = [
        'nombre_permiso', 
        'ruta_permiso',  
        'estado_permiso',    
    ];
    protected $guarded = [];
    use HasFactory;
}

app/Http/Controllers/permisoController.php
<?php

namespace App\Http\Controllers;

use App\Models\permiso;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class permisoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permisos = permiso::all();
        return view('admin/permiso/index', ['permisos' => $permisos]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin/permiso/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $permiso = new permiso();
        $permiso->nombre_permiso = $request->get('nombre_permiso');
        $permiso->ruta_permiso = $request->get('ruta_permiso');
        $permiso->estado_permiso = 'Activo';
        $permiso->save();
        return redirect('permiso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pemriso = permiso::all();
        return view ('permiso', ['pemriso'=> $pemriso]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permiso = permiso::find($id);
        return view('admin/permiso/edit', ['permiso' => $permiso]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permiso = permiso::find($id);
        $permiso->nombre_permiso = $request->get('nombre_permiso');
        $permiso->ruta_permiso = $request->get('ruta_permiso');
        $permiso->estado_permiso = $request->get('estado_permiso');
        $permiso->update();
        return redirect()->route('permiso.index')->with('info','¡Datos actualizados exitosamente!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(permiso $permiso)
    {
        $permiso->delete();
        return redirect()->route('permiso.index', $permiso)->with('info','¡Dato eliminado exitosamente!');
    }
}

resources/views/admin/permiso/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <form class="p-4" action="{{route('permiso.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre de la permiso</label>
                    <input type="text" class="form-control" name="nombre_permiso" aria-describedby="emailHelp" required>
                    @error('nombre')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Ruta de la permiso</label>
                    <input type="text" class="form-control" name="ruta_permiso" aria-describedby="emailHelp">
                    @error('ruta')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="d-flex justify-content-between">
                <input type="submit" class="btn btn-primary" value="Guardar">
                    <a type="button" class="btn btn-success" href="/permiso">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
console.log('Hi!');
</script>
@stop

resources/views/admin/permiso/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
@if(session('info'))
<div class="bg-success">
    <strong>{{session('info')}}</strong>
</div>
@endif
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <form class="p-4" action="{{route('permiso.update', $permiso)}}" method="POST" enctype="multipart/form-data">
                @csrf
                
                @method('put')
                <div class="form-group">
                    <label for="exampleInputEmail1">Nombre del permiso</label>
                    <input type="text" id="nombre" class="form-control" name="nombre_permiso" value="{{$permiso->nombre_permiso}}">
                    @error('nombre')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Ruta del permiso</label>
                    <input type="text" id="ruta" class="form-control" name="ruta_permiso" value="{{$permiso->ruta_permiso}}">
                    @error('rura')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Estado</label>
                    <input type="text" id="ruta" class="form-control" name="estado_permiso" value="{{$permiso->estado_permiso}}">
                    @error('estado')
                        <small class="text-danger">{{$message}}</small>
                    @enderror
                </div>
                <div class="d-flex justify-content-between">
                <input type="submit" class="btn btn-primary">
                    <a type="button" class="btn btn-success" href="/permiso">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
console.log('Hi!');
</script>
@stop

resources/views/admin/permiso/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
@if(session('info'))
<div id="toast" class="alert alert-success" style="height: 10vh">
    <strong>{{session('info')}}</strong>
    <button onclick="cerrar()" type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
@endif
<div class="p-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
            <div class="p-4">
                <div class="w-100 mb-4 row justify-content-md-between">
                    <label class="h4">Lista de permisos</label>
                    <a type="button" class="btn btn-success" href="permiso/create">Ingresar</a>
                </div>
                <!--Contenedor de listado de permisos-->
                @if($permisos->count())
                    <div>
                        <table id="permisos" class="table table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col text-center">Nº</th>
                                    <th scope="col">Permiso</th>
                                    <th scope="col">Estado</th>
                                    <th scope="col text-center"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($permisos as $permiso)
                                <tr>
                                    <td>{{$permiso->id}}</td>
                                    <td>{{$permiso->nombre_permiso}}</td>
                                    <td>{{$permiso->estado_permiso}}</td>
                                    <td>
                                        <div class="w-100 row justify-content-center">
                                            <a class="btn btn-primary mr-2" href="{{route('permiso.edit', $permiso)}}">Editar</a>
                                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                                Eliminar
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else 
                    <div class="text-center">
                        <strong>No hay ningún registros</strong>
                    </div>
                @endif
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Eliminar Registro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ¿Desea eliminar el registro?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    @if($permisos->count())
                        <form action="{{route('permiso.destroy', $permiso)}}" method="POST">
                            <!--<button type="submit" class="btn btn-danger">Eliminar</button>-->
                            <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                                Eliminar
                            </button>
                            @csrf
                            @method('delete')
                        </form>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@stop

@section('js')
</script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.7/js/responsive.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<script>
    $(document).ready(function() {
        $('#permiso').DataTable({
            responsive: true,
            autowidth: false
        });
    });
</script>
<script>
    function cerrar() {
        document.getElementById("toast").style.display = "none";
    }
</script>
@stop